["datas"] = {
    [1] = {
        ["cdrate"] = 1,
        ["id"] = 1,
        ["levellimit"] = 1,
        ["name_short"] = "",
        ["contentstyle"] = "Item0",
        ["name"] = "System",
        ["cachedount"] = 50,
        ["tbxid"] = 1,
        ["namestyle"] = "[Item0]【System】[/Item0]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [2] = {
        ["cdrate"] = 1,
        ["id"] = 2,
        ["levellimit"] = 1,
        ["name_short"] = "Party",
        ["contentstyle"] = "Item2",
        ["name"] = "Party",
        ["cachedount"] = 50,
        ["tbxid"] = 2,
        ["namestyle"] = "[Item2]【Party】[/Item2]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [3] = {
        ["cdrate"] = 1,
        ["id"] = 3,
        ["levellimit"] = 1,
        ["name_short"] = "Guild",
        ["contentstyle"] = "Item3",
        ["name"] = "Guild",
        ["cachedount"] = 50,
        ["tbxid"] = 3,
        ["namestyle"] = "[Item3]【Guild】[/Item3]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [4] = {
        ["cdrate"] = 1,
        ["id"] = 4,
        ["levellimit"] = 5,
        ["name_short"] = "Region",
        ["contentstyle"] = "Item5",
        ["name"] = "Region",
        ["cachedount"] = 50,
        ["tbxid"] = 4,
        ["namestyle"] = "[Item5]【Region】[/Item5]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [5] = {
        ["cdrate"] = 3,
        ["id"] = 5,
        ["levellimit"] = 1,
        ["name_short"] = "World",
        ["contentstyle"] = "Item4",
        ["name"] = "World",
        ["cachedount"] = 50,
        ["tbxid"] = 5,
        ["namestyle"] = "[Item4]【World】[/Item4]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [6] = {
        ["cdrate"] = 1,
        ["id"] = 6,
        ["levellimit"] = 1,
        ["name_short"] = "Nearby",
        ["contentstyle"] = "Item1",
        ["name"] = "Nearby",
        ["cachedount"] = 50,
        ["tbxid"] = 6,
        ["namestyle"] = "[Item1]【Nearby】[/Item1]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [7] = {
        ["cdrate"] = 1,
        ["id"] = 7,
        ["levellimit"] = 1,
        ["name_short"] = "Whisper",
        ["contentstyle"] = "",
        ["name"] = "Whisper",
        ["cachedount"] = 50,
        ["tbxid"] = 7,
        ["namestyle"] = "",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [8] = {
        ["cdrate"] = 1,
        ["id"] = 8,
        ["levellimit"] = 1,
        ["name_short"] = "GM chat",
        ["contentstyle"] = "",
        ["name"] = "GM chat",
        ["cachedount"] = 50,
        ["tbxid"] = 8,
        ["namestyle"] = "",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [9] = {
        ["cdrate"] = 1,
        ["id"] = 9,
        ["levellimit"] = 1,
        ["name_short"] = "Colosseum",
        ["contentstyle"] = "",
        ["name"] = "Colosseum",
        ["cachedount"] = 50,
        ["tbxid"] = 9,
        ["namestyle"] = "",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [10] = {
        ["cdrate"] = 1,
        ["id"] = 10,
        ["levellimit"] = 1,
        ["name_short"] = "Secret language",
        ["contentstyle"] = "",
        ["name"] = "Secret language",
        ["cachedount"] = 50,
        ["tbxid"] = 10,
        ["namestyle"] = "",
        ["wordlimit"] = 150,
        ["cost"] = ""
    }
}

----- end of message -----
