["datas"] = {
    [1] = {
        ["cdrate"] = 1,
        ["id"] = 1,
        ["levellimit"] = 1,
        ["name_short"] = "",
        ["contentstyle"] = "Item0",
        ["name"] = "系统",
        ["cachedount"] = 50,
        ["tbxid"] = 1,
        ["namestyle"] = "[Item0]【系统】[/Item0]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [2] = {
        ["cdrate"] = 1,
        ["id"] = 2,
        ["levellimit"] = 1,
        ["name_short"] = "队伍",
        ["contentstyle"] = "Item2",
        ["name"] = "队伍",
        ["cachedount"] = 50,
        ["tbxid"] = 2,
        ["namestyle"] = "[Item2]【队伍】[/Item2]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [3] = {
        ["cdrate"] = 1,
        ["id"] = 3,
        ["levellimit"] = 1,
        ["name_short"] = "家族",
        ["contentstyle"] = "Item3",
        ["name"] = "家族",
        ["cachedount"] = 50,
        ["tbxid"] = 3,
        ["namestyle"] = "[Item3]【家族】[/Item3]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [4] = {
        ["cdrate"] = 1,
        ["id"] = 4,
        ["levellimit"] = 5,
        ["name_short"] = "阵营",
        ["contentstyle"] = "Item5",
        ["name"] = "阵营",
        ["cachedount"] = 50,
        ["tbxid"] = 4,
        ["namestyle"] = "[Item5]【阵营】[/Item5]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [5] = {
        ["cdrate"] = 3,
        ["id"] = 5,
        ["levellimit"] = 1,
        ["name_short"] = "世界",
        ["contentstyle"] = "Item4",
        ["name"] = "世界",
        ["cachedount"] = 50,
        ["tbxid"] = 5,
        ["namestyle"] = "[Item4]【世界】[/Item4]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [6] = {
        ["cdrate"] = 1,
        ["id"] = 6,
        ["levellimit"] = 1,
        ["name_short"] = "附近",
        ["contentstyle"] = "Item1",
        ["name"] = "附近",
        ["cachedount"] = 50,
        ["tbxid"] = 6,
        ["namestyle"] = "[Item1]【附近】[/Item1]",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [7] = {
        ["cdrate"] = 1,
        ["id"] = 7,
        ["levellimit"] = 1,
        ["name_short"] = "私聊",
        ["contentstyle"] = "",
        ["name"] = "私聊",
        ["cachedount"] = 50,
        ["tbxid"] = 7,
        ["namestyle"] = "",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [8] = {
        ["cdrate"] = 1,
        ["id"] = 8,
        ["levellimit"] = 1,
        ["name_short"] = "GM聊天",
        ["contentstyle"] = "",
        ["name"] = "GM聊天",
        ["cachedount"] = 50,
        ["tbxid"] = 8,
        ["namestyle"] = "",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [9] = {
        ["cdrate"] = 1,
        ["id"] = 9,
        ["levellimit"] = 1,
        ["name_short"] = "角斗场",
        ["contentstyle"] = "",
        ["name"] = "角斗场",
        ["cachedount"] = 50,
        ["tbxid"] = 9,
        ["namestyle"] = "",
        ["wordlimit"] = 150,
        ["cost"] = ""
    },
    [10] = {
        ["cdrate"] = 1,
        ["id"] = 10,
        ["levellimit"] = 1,
        ["name_short"] = "密语",
        ["contentstyle"] = "",
        ["name"] = "密语",
        ["cachedount"] = 50,
        ["tbxid"] = 10,
        ["namestyle"] = "",
        ["wordlimit"] = 150,
        ["cost"] = ""
    }
}

----- end of message -----
