#pragma once
class TableContainer
{

public:
	enum eTABLE
	{
		// Character
		TABLE_ADVENTURE_COPYMAP = 0,
		TABLE_ATTRIBUTE_CONFIG,
		TABLE_AVATAR_CONFIG,
		TABLE_BATTLE_CONFIG,
		TABLE_BUILDING_DATA,
		TABLE_CARDDATA_CONFIG,
		TABLE_CARDEFFECT_CONFIG,
		TABLE_CAREERLV,
		TABLE_CHARSTATE,
		TABLE_CHAT_CHANNEL,
		TABLE_CONVENIENT,

		// Item
		TABLE_COORDS_ARENA_CONFIG,
		TABLE_COPYMAP_EVENT,
		TABLE_COPYMAP_INFO,
		TABLE_COPYMAP_MASTER,
		TABLE_CUTSCENE,
		TABLE_DEVICE_SETTING,
		TABLE_DIALOGUE_CONFIG,
		TABLE_DNACHIP_CONFIG,
		TABLE_DNASLOT_CONFIG,
		TABLE_DYAMIC_TEXT,

		// Misc
		TABLE_ENTANGLEMENT_CONFIG,
		TABLE_EQUIP_SUFFIX,
		TABLE_EQUIPS,
		TABLE_ESC_CONF,
		TABLE_EVENT_CONFIG,

		// Party
		TABLE_EVOLUTION_CONFIG,

		// Quest
		TABLE_FACE_CONFIG,
		TABLE_GENE_REMAKE,
		TABLE_GROWTARGET_CONFIG,
		TABLE_GUIDE,
		TABLE_HEROPANEL_MAXIMUM,

		// Rule
		TABLE_HEROES,
		TABLE_ILLEGAL_WORDS,
		TABLE_KEY,

		// Skill
		TABLE_LEVEL_CONFIG,
		TABLE_LOADING_TIPS,
		TABLE_LOOKS_CONFIG,

		// Text
		TABLE_MANUFACTURE,
		TABLE_NAMEPOOL,
		TABLE_NEW_USER,
		TABLE_NPC_DATA,

		// World
		TABLE_OBJECTS,
		TABLE_PATHWAY, //NPC Spawns
		TABLE_PLAYER_LEVEL_CONFIG,
		TABLE_QUEST_CONFIG,
		TABLE_QUIZDATA_CONFIG,
		TABLE_RANKPK_LEVEL,
		TABLE_RELATION,

		// GraphicData
		TABLE_REWARD_LEVEL,
		TABLE_RUNE_CONFIG,

		// World Data
		TABLE_SCREENSETTING,

		// Portal Data
		TABLE_SEVENTARGET_CONFIG, //7 Day login Shits

		TABLE_SKILL_DATA,

		TABLE_SKILL_GUILD,
		TABLE_SKILL_STAGE,

		TABLE_SKILL_SHOW,
		TABLE_SUMMON_PET,
		TABLE_SUMMON_PET_LEVELUP,

		TABLE_TELEPORT,

		TABLE_TEXT_CONFIG,
		TABLE_UI_MAP_INFO,
		TABLE_UNLOCK_CONFIG,
		TABLE_VIPCARD_CONFIG,

		TABLE_COUNT
	};
	static TableContainer& instance();

	//void Load(const eTABLE table, const std::string_view file);
	//const TableNPC* GetNpcTable() const;

};

#define sTBL TableContainer::instance()