["datas"] = {
    [1] = {
        ["rank_awards"] = "",
        ["icon"] = "rank4",
        ["id"] = 1,
        ["icon_small"] = "rank4_1",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 1,
        ["tbxid"] = 1,
        ["season_reward"] = "99004-1-1",
        ["name"] = "Warrior1",
        ["max_star"] = 2
    },
    [2] = {
        ["rank_awards"] = "",
        ["icon"] = "rank4",
        ["id"] = 2,
        ["icon_small"] = "rank4_2",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 1,
        ["tbxid"] = 2,
        ["season_reward"] = "99004-1-1;210012-5-1",
        ["name"] = "Warrior2",
        ["max_star"] = 2
    },
    [3] = {
        ["rank_awards"] = "",
        ["icon"] = "rank4",
        ["id"] = 3,
        ["icon_small"] = "rank4_3",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 1,
        ["tbxid"] = 3,
        ["season_reward"] = "99004-1-1;400050-5-1",
        ["name"] = "Warrior3",
        ["max_star"] = 2
    },
    [4] = {
        ["rank_awards"] = "",
        ["icon"] = "rank4",
        ["id"] = 4,
        ["icon_small"] = "rank4_4",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 1,
        ["tbxid"] = 4,
        ["season_reward"] = "99004-1-1;400051-5-1",
        ["name"] = "Warrior4",
        ["max_star"] = 2
    },
    [5] = {
        ["rank_awards"] = "",
        ["icon"] = "rank4",
        ["id"] = 5,
        ["icon_small"] = "rank4_5",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 1,
        ["tbxid"] = 5,
        ["season_reward"] = "99005-1-1;210014-5-1",
        ["name"] = "Warrior5",
        ["max_star"] = 2
    },
    [6] = {
        ["rank_awards"] = "",
        ["icon"] = "rank3",
        ["id"] = 6,
        ["icon_small"] = "rank3_1",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 0,
        ["tbxid"] = 6,
        ["season_reward"] = "99005-1-1;400052-5-1",
        ["name"] = "Grandmaster1",
        ["max_star"] = 4
    },
    [7] = {
        ["rank_awards"] = "",
        ["icon"] = "rank3",
        ["id"] = 7,
        ["icon_small"] = "rank3_2",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 0,
        ["tbxid"] = 7,
        ["season_reward"] = "99005-1-1;400053-5-1",
        ["name"] = "Grandmaster2",
        ["max_star"] = 4
    },
    [8] = {
        ["rank_awards"] = "",
        ["icon"] = "rank3",
        ["id"] = 8,
        ["icon_small"] = "rank3_3",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 0,
        ["tbxid"] = 8,
        ["season_reward"] = "99005-1-1;400054-1-1",
        ["name"] = "Grandmaster3",
        ["max_star"] = 4
    },
    [9] = {
        ["rank_awards"] = "",
        ["icon"] = "rank3",
        ["id"] = 9,
        ["icon_small"] = "rank3_4",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 0,
        ["tbxid"] = 9,
        ["season_reward"] = "99005-1-1;400055-1-1",
        ["name"] = "Grandmaster4",
        ["max_star"] = 4
    },
    [10] = {
        ["rank_awards"] = "",
        ["icon"] = "rank3",
        ["id"] = 10,
        ["icon_small"] = "rank3_5",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 0,
        ["tbxid"] = 10,
        ["season_reward"] = "99005-1-1;210015-5-1",
        ["name"] = "Grandmaster5",
        ["max_star"] = 4
    },
    [11] = {
        ["rank_awards"] = "",
        ["icon"] = "rank2",
        ["id"] = 11,
        ["icon_small"] = "rank2_1",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 0,
        ["tbxid"] = 11,
        ["season_reward"] = "99004-1-1;400056-1-1",
        ["name"] = "Guru1",
        ["max_star"] = 5
    },
    [12] = {
        ["rank_awards"] = "",
        ["icon"] = "rank2",
        ["id"] = 12,
        ["icon_small"] = "rank2_2",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 0,
        ["tbxid"] = 12,
        ["season_reward"] = "99004-1-1;400057-1-1",
        ["name"] = "Guru2",
        ["max_star"] = 5
    },
    [13] = {
        ["rank_awards"] = "",
        ["icon"] = "rank2",
        ["id"] = 13,
        ["icon_small"] = "rank2_3",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 0,
        ["tbxid"] = 13,
        ["season_reward"] = "99006-1-0;210016-5-1",
        ["name"] = "Guru3",
        ["max_star"] = 5
    },
    [14] = {
        ["rank_awards"] = "",
        ["icon"] = "rank1",
        ["id"] = 14,
        ["icon_small"] = "",
        ["histroy_rank_reward"] = "",
        ["continue_win_reward_star"] = 0,
        ["tbxid"] = 14,
        ["season_reward"] = "99006-1-0;210017-3-1",
        ["name"] = "Strongest warrior",
        ["max_star"] = 0
    }
}

----- end of message -----
