// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: illegalword.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_illegalword_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_illegalword_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_illegalword_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_illegalword_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_illegalword_2eproto;
namespace pb {
class illegalword;
class illegalwordDefaultTypeInternal;
extern illegalwordDefaultTypeInternal _illegalword_default_instance_;
class illegalword_t_illegalword_config;
class illegalword_t_illegalword_configDefaultTypeInternal;
extern illegalword_t_illegalword_configDefaultTypeInternal _illegalword_t_illegalword_config_default_instance_;
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::illegalword* Arena::CreateMaybeMessage<::pb::illegalword>(Arena*);
template<> ::pb::illegalword_t_illegalword_config* Arena::CreateMaybeMessage<::pb::illegalword_t_illegalword_config>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {

// ===================================================================

class illegalword_t_illegalword_config :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.illegalword.t_illegalword_config) */ {
 public:
  illegalword_t_illegalword_config();
  virtual ~illegalword_t_illegalword_config();

  illegalword_t_illegalword_config(const illegalword_t_illegalword_config& from);
  illegalword_t_illegalword_config(illegalword_t_illegalword_config&& from) noexcept
    : illegalword_t_illegalword_config() {
    *this = ::std::move(from);
  }

  inline illegalword_t_illegalword_config& operator=(const illegalword_t_illegalword_config& from) {
    CopyFrom(from);
    return *this;
  }
  inline illegalword_t_illegalword_config& operator=(illegalword_t_illegalword_config&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const illegalword_t_illegalword_config& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const illegalword_t_illegalword_config* internal_default_instance() {
    return reinterpret_cast<const illegalword_t_illegalword_config*>(
               &_illegalword_t_illegalword_config_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(illegalword_t_illegalword_config& a, illegalword_t_illegalword_config& b) {
    a.Swap(&b);
  }
  inline void Swap(illegalword_t_illegalword_config* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline illegalword_t_illegalword_config* New() const final {
    return CreateMaybeMessage<illegalword_t_illegalword_config>(nullptr);
  }

  illegalword_t_illegalword_config* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<illegalword_t_illegalword_config>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const illegalword_t_illegalword_config& from);
  void MergeFrom(const illegalword_t_illegalword_config& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(illegalword_t_illegalword_config* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.illegalword.t_illegalword_config";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_illegalword_2eproto);
    return ::descriptor_table_illegalword_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWordFieldNumber = 3,
    kTbxidFieldNumber = 1,
    kIdFieldNumber = 2,
    kDisplayFieldNumber = 4,
  };
  // required string word = 3;
  bool has_word() const;
  private:
  bool _internal_has_word() const;
  public:
  void clear_word();
  const std::string& word() const;
  void set_word(const std::string& value);
  void set_word(std::string&& value);
  void set_word(const char* value);
  void set_word(const char* value, size_t size);
  std::string* mutable_word();
  std::string* release_word();
  void set_allocated_word(std::string* word);
  private:
  const std::string& _internal_word() const;
  void _internal_set_word(const std::string& value);
  std::string* _internal_mutable_word();
  public:

  // required uint32 tbxid = 1 [default = 0];
  bool has_tbxid() const;
  private:
  bool _internal_has_tbxid() const;
  public:
  void clear_tbxid();
  ::PROTOBUF_NAMESPACE_ID::uint32 tbxid() const;
  void set_tbxid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_tbxid() const;
  void _internal_set_tbxid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // required uint32 id = 2 [default = 0];
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // required uint32 display = 4;
  bool has_display() const;
  private:
  bool _internal_has_display() const;
  public:
  void clear_display();
  ::PROTOBUF_NAMESPACE_ID::uint32 display() const;
  void set_display(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_display() const;
  void _internal_set_display(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:pb.illegalword.t_illegalword_config)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr word_;
  ::PROTOBUF_NAMESPACE_ID::uint32 tbxid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 display_;
  friend struct ::TableStruct_illegalword_2eproto;
};
// -------------------------------------------------------------------

class illegalword :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.illegalword) */ {
 public:
  illegalword();
  virtual ~illegalword();

  illegalword(const illegalword& from);
  illegalword(illegalword&& from) noexcept
    : illegalword() {
    *this = ::std::move(from);
  }

  inline illegalword& operator=(const illegalword& from) {
    CopyFrom(from);
    return *this;
  }
  inline illegalword& operator=(illegalword&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const illegalword& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const illegalword* internal_default_instance() {
    return reinterpret_cast<const illegalword*>(
               &_illegalword_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(illegalword& a, illegalword& b) {
    a.Swap(&b);
  }
  inline void Swap(illegalword* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline illegalword* New() const final {
    return CreateMaybeMessage<illegalword>(nullptr);
  }

  illegalword* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<illegalword>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const illegalword& from);
  void MergeFrom(const illegalword& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(illegalword* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.illegalword";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_illegalword_2eproto);
    return ::descriptor_table_illegalword_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef illegalword_t_illegalword_config t_illegalword_config;

  // accessors -------------------------------------------------------

  enum : int {
    kDatasFieldNumber = 1,
  };
  // repeated .pb.illegalword.t_illegalword_config datas = 1;
  int datas_size() const;
  private:
  int _internal_datas_size() const;
  public:
  void clear_datas();
  ::pb::illegalword_t_illegalword_config* mutable_datas(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::illegalword_t_illegalword_config >*
      mutable_datas();
  private:
  const ::pb::illegalword_t_illegalword_config& _internal_datas(int index) const;
  ::pb::illegalword_t_illegalword_config* _internal_add_datas();
  public:
  const ::pb::illegalword_t_illegalword_config& datas(int index) const;
  ::pb::illegalword_t_illegalword_config* add_datas();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::illegalword_t_illegalword_config >&
      datas() const;

  // @@protoc_insertion_point(class_scope:pb.illegalword)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::illegalword_t_illegalword_config > datas_;
  friend struct ::TableStruct_illegalword_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// illegalword_t_illegalword_config

// required uint32 tbxid = 1 [default = 0];
inline bool illegalword_t_illegalword_config::_internal_has_tbxid() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool illegalword_t_illegalword_config::has_tbxid() const {
  return _internal_has_tbxid();
}
inline void illegalword_t_illegalword_config::clear_tbxid() {
  tbxid_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 illegalword_t_illegalword_config::_internal_tbxid() const {
  return tbxid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 illegalword_t_illegalword_config::tbxid() const {
  // @@protoc_insertion_point(field_get:pb.illegalword.t_illegalword_config.tbxid)
  return _internal_tbxid();
}
inline void illegalword_t_illegalword_config::_internal_set_tbxid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  tbxid_ = value;
}
inline void illegalword_t_illegalword_config::set_tbxid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_tbxid(value);
  // @@protoc_insertion_point(field_set:pb.illegalword.t_illegalword_config.tbxid)
}

// required uint32 id = 2 [default = 0];
inline bool illegalword_t_illegalword_config::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool illegalword_t_illegalword_config::has_id() const {
  return _internal_has_id();
}
inline void illegalword_t_illegalword_config::clear_id() {
  id_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 illegalword_t_illegalword_config::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 illegalword_t_illegalword_config::id() const {
  // @@protoc_insertion_point(field_get:pb.illegalword.t_illegalword_config.id)
  return _internal_id();
}
inline void illegalword_t_illegalword_config::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  id_ = value;
}
inline void illegalword_t_illegalword_config::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:pb.illegalword.t_illegalword_config.id)
}

// required string word = 3;
inline bool illegalword_t_illegalword_config::_internal_has_word() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool illegalword_t_illegalword_config::has_word() const {
  return _internal_has_word();
}
inline void illegalword_t_illegalword_config::clear_word() {
  word_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& illegalword_t_illegalword_config::word() const {
  // @@protoc_insertion_point(field_get:pb.illegalword.t_illegalword_config.word)
  return _internal_word();
}
inline void illegalword_t_illegalword_config::set_word(const std::string& value) {
  _internal_set_word(value);
  // @@protoc_insertion_point(field_set:pb.illegalword.t_illegalword_config.word)
}
inline std::string* illegalword_t_illegalword_config::mutable_word() {
  // @@protoc_insertion_point(field_mutable:pb.illegalword.t_illegalword_config.word)
  return _internal_mutable_word();
}
inline const std::string& illegalword_t_illegalword_config::_internal_word() const {
  return word_.GetNoArena();
}
inline void illegalword_t_illegalword_config::_internal_set_word(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  word_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void illegalword_t_illegalword_config::set_word(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  word_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.illegalword.t_illegalword_config.word)
}
inline void illegalword_t_illegalword_config::set_word(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  word_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.illegalword.t_illegalword_config.word)
}
inline void illegalword_t_illegalword_config::set_word(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  word_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.illegalword.t_illegalword_config.word)
}
inline std::string* illegalword_t_illegalword_config::_internal_mutable_word() {
  _has_bits_[0] |= 0x00000001u;
  return word_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* illegalword_t_illegalword_config::release_word() {
  // @@protoc_insertion_point(field_release:pb.illegalword.t_illegalword_config.word)
  if (!_internal_has_word()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return word_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void illegalword_t_illegalword_config::set_allocated_word(std::string* word) {
  if (word != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  word_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), word);
  // @@protoc_insertion_point(field_set_allocated:pb.illegalword.t_illegalword_config.word)
}

// required uint32 display = 4;
inline bool illegalword_t_illegalword_config::_internal_has_display() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool illegalword_t_illegalword_config::has_display() const {
  return _internal_has_display();
}
inline void illegalword_t_illegalword_config::clear_display() {
  display_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 illegalword_t_illegalword_config::_internal_display() const {
  return display_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 illegalword_t_illegalword_config::display() const {
  // @@protoc_insertion_point(field_get:pb.illegalword.t_illegalword_config.display)
  return _internal_display();
}
inline void illegalword_t_illegalword_config::_internal_set_display(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  display_ = value;
}
inline void illegalword_t_illegalword_config::set_display(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_display(value);
  // @@protoc_insertion_point(field_set:pb.illegalword.t_illegalword_config.display)
}

// -------------------------------------------------------------------

// illegalword

// repeated .pb.illegalword.t_illegalword_config datas = 1;
inline int illegalword::_internal_datas_size() const {
  return datas_.size();
}
inline int illegalword::datas_size() const {
  return _internal_datas_size();
}
inline void illegalword::clear_datas() {
  datas_.Clear();
}
inline ::pb::illegalword_t_illegalword_config* illegalword::mutable_datas(int index) {
  // @@protoc_insertion_point(field_mutable:pb.illegalword.datas)
  return datas_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::illegalword_t_illegalword_config >*
illegalword::mutable_datas() {
  // @@protoc_insertion_point(field_mutable_list:pb.illegalword.datas)
  return &datas_;
}
inline const ::pb::illegalword_t_illegalword_config& illegalword::_internal_datas(int index) const {
  return datas_.Get(index);
}
inline const ::pb::illegalword_t_illegalword_config& illegalword::datas(int index) const {
  // @@protoc_insertion_point(field_get:pb.illegalword.datas)
  return _internal_datas(index);
}
inline ::pb::illegalword_t_illegalword_config* illegalword::_internal_add_datas() {
  return datas_.Add();
}
inline ::pb::illegalword_t_illegalword_config* illegalword::add_datas() {
  // @@protoc_insertion_point(field_add:pb.illegalword.datas)
  return _internal_add_datas();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::illegalword_t_illegalword_config >&
illegalword::datas() const {
  // @@protoc_insertion_point(field_list:pb.illegalword.datas)
  return datas_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_illegalword_2eproto
