// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relation_tbx.proto

#include "relation_tbx.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_relation_5ftbx_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_relation_tbx_t_relation_relation_5ftbx_2eproto;
namespace pb {
class relation_tbx_t_relationDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<relation_tbx_t_relation> _instance;
} _relation_tbx_t_relation_default_instance_;
class relation_tbxDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<relation_tbx> _instance;
} _relation_tbx_default_instance_;
}  // namespace pb
static void InitDefaultsscc_info_relation_tbx_relation_5ftbx_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::_relation_tbx_default_instance_;
    new (ptr) ::pb::relation_tbx();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::relation_tbx::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_relation_tbx_relation_5ftbx_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_relation_tbx_relation_5ftbx_2eproto}, {
      &scc_info_relation_tbx_t_relation_relation_5ftbx_2eproto.base,}};

static void InitDefaultsscc_info_relation_tbx_t_relation_relation_5ftbx_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::_relation_tbx_t_relation_default_instance_;
    new (ptr) ::pb::relation_tbx_t_relation();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::relation_tbx_t_relation::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_relation_tbx_t_relation_relation_5ftbx_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_relation_tbx_t_relation_relation_5ftbx_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_relation_5ftbx_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_relation_5ftbx_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_relation_5ftbx_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_relation_5ftbx_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, tbxid_),
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, id_),
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, valuetype_),
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, addvalue_),
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, subvalue_),
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, daytimes_),
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, lasttime_),
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx_t_relation, rangelimit_),
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  0,
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pb::relation_tbx, datas_),
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 13, sizeof(::pb::relation_tbx_t_relation)},
  { 21, 27, sizeof(::pb::relation_tbx)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pb::_relation_tbx_t_relation_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pb::_relation_tbx_default_instance_),
};

const char descriptor_table_protodef_relation_5ftbx_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022relation_tbx.proto\022\002pb\"\331\001\n\014relation_tb"
  "x\022*\n\005datas\030\001 \003(\0132\033.pb.relation_tbx.t_rel"
  "ation\032\234\001\n\nt_relation\022\020\n\005tbxid\030\001 \002(\r:\0010\022\r"
  "\n\002id\030\002 \002(\r:\0010\022\021\n\tvaluetype\030\003 \002(\r\022\020\n\010addv"
  "alue\030\004 \002(\r\022\020\n\010subvalue\030\005 \002(\r\022\020\n\010daytimes"
  "\030\006 \002(\r\022\020\n\010lasttime\030\007 \002(\r\022\022\n\nrangelimit\030\010"
  " \002(\t"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_relation_5ftbx_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_relation_5ftbx_2eproto_sccs[2] = {
  &scc_info_relation_tbx_relation_5ftbx_2eproto.base,
  &scc_info_relation_tbx_t_relation_relation_5ftbx_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_relation_5ftbx_2eproto_once;
static bool descriptor_table_relation_5ftbx_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_relation_5ftbx_2eproto = {
  &descriptor_table_relation_5ftbx_2eproto_initialized, descriptor_table_protodef_relation_5ftbx_2eproto, "relation_tbx.proto", 244,
  &descriptor_table_relation_5ftbx_2eproto_once, descriptor_table_relation_5ftbx_2eproto_sccs, descriptor_table_relation_5ftbx_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_relation_5ftbx_2eproto::offsets,
  file_level_metadata_relation_5ftbx_2eproto, 2, file_level_enum_descriptors_relation_5ftbx_2eproto, file_level_service_descriptors_relation_5ftbx_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_relation_5ftbx_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_relation_5ftbx_2eproto)), true);
namespace pb {

// ===================================================================

void relation_tbx_t_relation::InitAsDefaultInstance() {
}
class relation_tbx_t_relation::_Internal {
 public:
  using HasBits = decltype(std::declval<relation_tbx_t_relation>()._has_bits_);
  static void set_has_tbxid(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_valuetype(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_addvalue(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_subvalue(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_daytimes(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_lasttime(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_rangelimit(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

relation_tbx_t_relation::relation_tbx_t_relation()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.relation_tbx.t_relation)
}
relation_tbx_t_relation::relation_tbx_t_relation(const relation_tbx_t_relation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  rangelimit_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_rangelimit()) {
    rangelimit_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.rangelimit_);
  }
  ::memcpy(&tbxid_, &from.tbxid_,
    static_cast<size_t>(reinterpret_cast<char*>(&lasttime_) -
    reinterpret_cast<char*>(&tbxid_)) + sizeof(lasttime_));
  // @@protoc_insertion_point(copy_constructor:pb.relation_tbx.t_relation)
}

void relation_tbx_t_relation::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_relation_tbx_t_relation_relation_5ftbx_2eproto.base);
  rangelimit_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&tbxid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lasttime_) -
      reinterpret_cast<char*>(&tbxid_)) + sizeof(lasttime_));
}

relation_tbx_t_relation::~relation_tbx_t_relation() {
  // @@protoc_insertion_point(destructor:pb.relation_tbx.t_relation)
  SharedDtor();
}

void relation_tbx_t_relation::SharedDtor() {
  rangelimit_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void relation_tbx_t_relation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const relation_tbx_t_relation& relation_tbx_t_relation::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_relation_tbx_t_relation_relation_5ftbx_2eproto.base);
  return *internal_default_instance();
}


void relation_tbx_t_relation::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.relation_tbx.t_relation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    rangelimit_.ClearNonDefaultToEmptyNoArena();
  }
  if (cached_has_bits & 0x000000feu) {
    ::memset(&tbxid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&lasttime_) -
        reinterpret_cast<char*>(&tbxid_)) + sizeof(lasttime_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* relation_tbx_t_relation::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required uint32 tbxid = 1 [default = 0];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_tbxid(&has_bits);
          tbxid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required uint32 id = 2 [default = 0];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_id(&has_bits);
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required uint32 valuetype = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_valuetype(&has_bits);
          valuetype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required uint32 addvalue = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_addvalue(&has_bits);
          addvalue_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required uint32 subvalue = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_subvalue(&has_bits);
          subvalue_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required uint32 daytimes = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_daytimes(&has_bits);
          daytimes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required uint32 lasttime = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          _Internal::set_has_lasttime(&has_bits);
          lasttime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string rangelimit = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          auto str = _internal_mutable_rangelimit();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "pb.relation_tbx.t_relation.rangelimit");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* relation_tbx_t_relation::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.relation_tbx.t_relation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 tbxid = 1 [default = 0];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_tbxid(), target);
  }

  // required uint32 id = 2 [default = 0];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_id(), target);
  }

  // required uint32 valuetype = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_valuetype(), target);
  }

  // required uint32 addvalue = 4;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_addvalue(), target);
  }

  // required uint32 subvalue = 5;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_subvalue(), target);
  }

  // required uint32 daytimes = 6;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_daytimes(), target);
  }

  // required uint32 lasttime = 7;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(7, this->_internal_lasttime(), target);
  }

  // required string rangelimit = 8;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_rangelimit().data(), static_cast<int>(this->_internal_rangelimit().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "pb.relation_tbx.t_relation.rangelimit");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_rangelimit(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.relation_tbx.t_relation)
  return target;
}

size_t relation_tbx_t_relation::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:pb.relation_tbx.t_relation)
  size_t total_size = 0;

  if (_internal_has_rangelimit()) {
    // required string rangelimit = 8;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rangelimit());
  }

  if (_internal_has_tbxid()) {
    // required uint32 tbxid = 1 [default = 0];
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_tbxid());
  }

  if (_internal_has_id()) {
    // required uint32 id = 2 [default = 0];
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_id());
  }

  if (_internal_has_valuetype()) {
    // required uint32 valuetype = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_valuetype());
  }

  if (_internal_has_addvalue()) {
    // required uint32 addvalue = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_addvalue());
  }

  if (_internal_has_subvalue()) {
    // required uint32 subvalue = 5;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_subvalue());
  }

  if (_internal_has_daytimes()) {
    // required uint32 daytimes = 6;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_daytimes());
  }

  if (_internal_has_lasttime()) {
    // required uint32 lasttime = 7;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_lasttime());
  }

  return total_size;
}
size_t relation_tbx_t_relation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.relation_tbx.t_relation)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x000000ff) ^ 0x000000ff) == 0) {  // All required fields are present.
    // required string rangelimit = 8;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rangelimit());

    // required uint32 tbxid = 1 [default = 0];
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_tbxid());

    // required uint32 id = 2 [default = 0];
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_id());

    // required uint32 valuetype = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_valuetype());

    // required uint32 addvalue = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_addvalue());

    // required uint32 subvalue = 5;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_subvalue());

    // required uint32 daytimes = 6;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_daytimes());

    // required uint32 lasttime = 7;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_lasttime());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void relation_tbx_t_relation::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.relation_tbx.t_relation)
  GOOGLE_DCHECK_NE(&from, this);
  const relation_tbx_t_relation* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<relation_tbx_t_relation>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.relation_tbx.t_relation)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.relation_tbx.t_relation)
    MergeFrom(*source);
  }
}

void relation_tbx_t_relation::MergeFrom(const relation_tbx_t_relation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.relation_tbx.t_relation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      rangelimit_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.rangelimit_);
    }
    if (cached_has_bits & 0x00000002u) {
      tbxid_ = from.tbxid_;
    }
    if (cached_has_bits & 0x00000004u) {
      id_ = from.id_;
    }
    if (cached_has_bits & 0x00000008u) {
      valuetype_ = from.valuetype_;
    }
    if (cached_has_bits & 0x00000010u) {
      addvalue_ = from.addvalue_;
    }
    if (cached_has_bits & 0x00000020u) {
      subvalue_ = from.subvalue_;
    }
    if (cached_has_bits & 0x00000040u) {
      daytimes_ = from.daytimes_;
    }
    if (cached_has_bits & 0x00000080u) {
      lasttime_ = from.lasttime_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void relation_tbx_t_relation::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.relation_tbx.t_relation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void relation_tbx_t_relation::CopyFrom(const relation_tbx_t_relation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.relation_tbx.t_relation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool relation_tbx_t_relation::IsInitialized() const {
  if ((_has_bits_[0] & 0x000000ff) != 0x000000ff) return false;
  return true;
}

void relation_tbx_t_relation::InternalSwap(relation_tbx_t_relation* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  rangelimit_.Swap(&other->rangelimit_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(tbxid_, other->tbxid_);
  swap(id_, other->id_);
  swap(valuetype_, other->valuetype_);
  swap(addvalue_, other->addvalue_);
  swap(subvalue_, other->subvalue_);
  swap(daytimes_, other->daytimes_);
  swap(lasttime_, other->lasttime_);
}

::PROTOBUF_NAMESPACE_ID::Metadata relation_tbx_t_relation::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void relation_tbx::InitAsDefaultInstance() {
}
class relation_tbx::_Internal {
 public:
  using HasBits = decltype(std::declval<relation_tbx>()._has_bits_);
};

relation_tbx::relation_tbx()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.relation_tbx)
}
relation_tbx::relation_tbx(const relation_tbx& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      datas_(from.datas_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pb.relation_tbx)
}

void relation_tbx::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_relation_tbx_relation_5ftbx_2eproto.base);
}

relation_tbx::~relation_tbx() {
  // @@protoc_insertion_point(destructor:pb.relation_tbx)
  SharedDtor();
}

void relation_tbx::SharedDtor() {
}

void relation_tbx::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const relation_tbx& relation_tbx::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_relation_tbx_relation_5ftbx_2eproto.base);
  return *internal_default_instance();
}


void relation_tbx::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.relation_tbx)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  datas_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* relation_tbx::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .pb.relation_tbx.t_relation datas = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_datas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* relation_tbx::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.relation_tbx)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.relation_tbx.t_relation datas = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_datas_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_datas(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.relation_tbx)
  return target;
}

size_t relation_tbx::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.relation_tbx)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb.relation_tbx.t_relation datas = 1;
  total_size += 1UL * this->_internal_datas_size();
  for (const auto& msg : this->datas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void relation_tbx::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.relation_tbx)
  GOOGLE_DCHECK_NE(&from, this);
  const relation_tbx* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<relation_tbx>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.relation_tbx)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.relation_tbx)
    MergeFrom(*source);
  }
}

void relation_tbx::MergeFrom(const relation_tbx& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.relation_tbx)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  datas_.MergeFrom(from.datas_);
}

void relation_tbx::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.relation_tbx)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void relation_tbx::CopyFrom(const relation_tbx& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.relation_tbx)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool relation_tbx::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(datas_)) return false;
  return true;
}

void relation_tbx::InternalSwap(relation_tbx* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  datas_.InternalSwap(&other->datas_);
}

::PROTOBUF_NAMESPACE_ID::Metadata relation_tbx::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::relation_tbx_t_relation* Arena::CreateMaybeMessage< ::pb::relation_tbx_t_relation >(Arena* arena) {
  return Arena::CreateInternal< ::pb::relation_tbx_t_relation >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::relation_tbx* Arena::CreateMaybeMessage< ::pb::relation_tbx >(Arena* arena) {
  return Arena::CreateInternal< ::pb::relation_tbx >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
